export interface MoodDefinition {
  name: string;
  color: string;
  scale: string;
  progression: string;
  desc: string;
}

export const MOOD_DEFINITIONS: MoodDefinition[] = [
  {
    name: "Heroic",
    color: "linear-gradient(135deg, #3b82f6, #4f46e5)",
    scale: "Lydian",
    progression: "I - II - I",
    desc: "Bright, soaring, and powerful. The raised 4th creates a sense of lifting.",
  },
  {
    name: "Dark",
    color: "linear-gradient(135deg, #3f3f46, #09090b)",
    scale: "Phrygian",
    progression: "i - bII - i",
    desc: "Tense, exotic, and heavy. The flat 2nd is the signature dark interval.",
  },
  {
    name: "Ethereal",
    color: "linear-gradient(135deg, #22d3ee, #60a5fa)",
    scale: "Lydian",
    progression: "maj7 - maj9",
    desc: "Dreamy, floating, and spacious. Focuses on extensions and open voicings.",
  },
  {
    name: "Sad",
    color: "linear-gradient(135deg, #1e40af, #312e81)",
    scale: "Aeolian (Natural Minor)",
    progression: "vi - IV - I - V",
    desc: "Emotional and melancholic. Classic minor-key vulnerability.",
  },
  {
    name: "Spooky",
    color: "linear-gradient(135deg, #581c87, #09090b)",
    scale: "Locrian",
    progression: "i dim - bII - iv",
    desc: "Unsettling, diminished, and unresolved. The most unstable mode.",
  },
  {
    name: "Joyful",
    color: "linear-gradient(135deg, #facc15, #f97316)",
    scale: "Ionian (Major)",
    progression: "I - IV - V",
    desc: "Bright, stable, and optimistic. The foundation of happy music.",
  },
  {
    name: "Mysterious",
    color: "linear-gradient(135deg, #4338ca, #6b21a8)",
    scale: "Acoustic (Lydian Dominant)",
    progression: "I7 - II7",
    desc: "Sophisticated and intriguing. Mixes major stability with unexpected color.",
  },
  {
    name: "Fiery",
    color: "linear-gradient(135deg, #dc2626, #ea580c)",
    scale: "Phrygian Dominant",
    progression: "i - bII - III - iv",
    desc: "Aggressive and passionate. Common in Flamenco and heavy styles.",
  },
  {
    name: "Peaceful",
    color: "linear-gradient(135deg, #34d399, #14b8a6)",
    scale: "Major Pentatonic",
    progression: "I - IV - I",
    desc: "Simple, organic, and grounded. Perfect for ambient or folk textures.",
  },
  {
    name: "Royal",
    color: "linear-gradient(135deg, #fbbf24, #ca8a04)",
    scale: "Mixolydian",
    progression: "I - bVII - IV",
    desc: "Noble and majestic. The major scale with a flattened 7th adds a rock edge.",
  },
  {
    name: "Cosmic",
    color: "linear-gradient(135deg, #312e81, #701a75)",
    scale: "Whole Tone",
    progression: "I+ - II+",
    desc: "Alien, symmetrical, and gravity-defying. Lacks a clear tonal center.",
  },
  {
    name: "Zen",
    color: "linear-gradient(135deg, #a8a29e, #57534e)",
    scale: "Hirajoshi",
    progression: "i - iv - i",
    desc: "Contemplative and minimal. Based on traditional Japanese koto colors.",
  },
  {
    name: "Cyberpunk",
    color: "linear-gradient(135deg, #d946ef, #2563eb)",
    scale: "Dorian",
    progression: "i7 - IV7",
    desc: "Neon-soaked and urban. Minor feel with a bright major 6th sparkle.",
  },
  {
    name: "Exotic",
    color: "linear-gradient(135deg, #fb923c, #ef4444)",
    scale: "Maqam Hijaz",
    progression: "i - bII - III",
    desc: "Distant and alluring. Uses augmented 2nd intervals for a desert sound.",
  },
  {
    name: "Melancholic",
    color: "linear-gradient(135deg, #52525b, #27272a)",
    scale: "Aeolian (Natural Minor)",
    progression: "i - bVI - i",
    desc: "Pensive and thoughtful. A more reserved version of sadness.",
  },
  {
    name: "Romantic",
    color: "linear-gradient(135deg, #ec4899, #e11d48)",
    scale: "Ionian (Major)",
    progression: "I - vi - IV - V",
    desc: "Sweet and sentimental. The classic ballad foundation.",
  },
  {
    name: "Tense",
    color: "linear-gradient(135deg, #c2410c, #09090b)",
    scale: "Locrian",
    progression: "i dim - bV - i dim",
    desc: "Urgent and stressful. Constantly pulling toward an unreachable home.",
  },
  {
    name: "Jazz Sophisticate",
    color: "linear-gradient(135deg, #3f3f46, #312e81)",
    scale: "Bebop Dominant",
    progression: "ii7 - V7 - Imaj7",
    desc: "Classy and complex. Fast-moving lines with chromatic passing tones.",
  },
  {
    name: "Folk Story",
    color: "linear-gradient(135deg, #b45309, #7c2d12)",
    scale: "Major Pentatonic",
    progression: "I - V - vi - IV",
    desc: "Narrative and warm. Simple intervals that tell a universal story.",
  },
  {
    name: "Gothic",
    color: "linear-gradient(135deg, #09090b, #450a0a)",
    scale: "Hungarian Minor",
    progression: "i - iv - V",
    desc: "Dramatic and orchestral. Dual augmented seconds create high drama.",
  },
  {
    name: "Dreamy",
    color: "linear-gradient(135deg, #c084fc, #22d3ee)",
    scale: "Lydian Augmented",
    progression: "Imaj7#5 - II",
    desc: "Hypnotic and surreal. An even more floating version of Lydian.",
  },
  {
    name: "Tropical",
    color: "linear-gradient(135deg, #fde047, #4ade80)",
    scale: "Major Pentatonic",
    progression: "I - ii - IV",
    desc: "Light, breezy, and rhythmic. Pure vacation energy.",
  },
  {
    name: "Ancient",
    color: "linear-gradient(135deg, #92400e, #713f12)",
    scale: "Phrygian Dominant",
    progression: "i - bII - III",
    desc: "Timeless and biblical. The sound of stone walls and old legends.",
  },
  {
    name: "Cyber-Noir",
    color: "linear-gradient(135deg, #1e3a8a, #18181b)",
    scale: "Dorian",
    progression: "i - IV - i",
    desc: "Melancholic but cool. Rain-slicked streets and neon reflections.",
  },
  {
    name: "Spiritual",
    color: "linear-gradient(135deg, #f97316, #d97706)",
    scale: "Raga Bhairav",
    progression: "I - bII - I",
    desc: "Devotional and deep. Based on morning ragas used for meditation.",
  },
  {
    name: "Gritty",
    color: "linear-gradient(135deg, #57534e, #292524)",
    scale: "Minor Blues",
    progression: "i - IV - bV - V",
    desc: "Raw and unpolished. The sound of struggle and resilience.",
  },
  {
    name: "Funky",
    color: "linear-gradient(135deg, #a855f7, #ec4899)",
    scale: "Dorian",
    progression: "i7 - IV7",
    desc: "Rhythmic and syncopated. Minor with a major 6th groove.",
  },
  {
    name: "Triumphant",
    color: "linear-gradient(135deg, #eab308, #f59e0b)",
    scale: "Ionian (Major)",
    progression: "I - V - IV - I",
    desc: "Heroic victory. Strong, stable major intervals.",
  },
  {
    name: "Haunting",
    color: "linear-gradient(135deg, #18181b, #3b0764)",
    scale: "Minor Pentatonic",
    progression: "i - bVI - i",
    desc: "Ghostly and lingering. Sparse intervals that leave a trail.",
  },
  {
    name: "Pastoral",
    color: "linear-gradient(135deg, #4ade80, #93c5fd)",
    scale: "Lydian",
    progression: "I - IV - I",
    desc: "Open fields and sunlight. Nature-inspired and expansive.",
  },
  {
    name: "Mechanical",
    color: "linear-gradient(135deg, #71717a, #3f3f46)",
    scale: "Whole Tone",
    progression: "I+ - II+",
    desc: "Repetitive and precise. Cold, calculated, and industrial.",
  },
  {
    name: "Oceanic",
    color: "linear-gradient(135deg, #60a5fa, #1d4ed8)",
    scale: "Lydian",
    progression: "maj9 - IVmaj7",
    desc: "Deep, vast, and fluid. Echoing the rhythmic pull of the tides.",
  },
];
