export interface FeatureDefinition {
  id: string;
  label: string;
  section: string;
  description: string;
  kind: "source" | "legacy";
  iconClass: string;
  iconTone: string;
  navTooltip: string;
  legacySectionLabel: string;
  sectionOrder: number;
  navOrder: number;
  previousNextOrder: number;
  legacyTitle: string;
  subtitle?: string;
  legacyNavId?: string;
  shellVisible: boolean;
  legacyView?: string;
}

const featureDefinitions: FeatureDefinition[] = [
  {
    id: "chords",
    label: "Diatonic Chords",
    section: "Harmony & Theory",
    description: "Source rewrite of scale-degree triads and seventh chords.",
    kind: "source",
    iconClass: "fa-music",
    iconTone: "indigo",
    navTooltip: "Diatonic triads and seventh chords",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 10,
    previousNextOrder: 10,
    legacyTitle: "Diatonic Chords",
    subtitle: "Interactive music theory exploration",
    shellVisible: true,
  },
  {
    id: "allchords",
    label: "All Chord Types",
    section: "Harmony & Theory",
    description: "Source rewrite of the chord formula and interval catalog.",
    kind: "source",
    iconClass: "fa-shapes",
    iconTone: "purple",
    navTooltip: "Chord qualities and extensions library",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 20,
    previousNextOrder: 20,
    legacyTitle: "All Chord Types",
    subtitle: "Chord qualities and extensions library",
    shellVisible: true,
  },
  {
    id: "voicings",
    label: "Chord Voicings",
    section: "Harmony & Theory",
    description: "Source rewrite of inversion, drop, shell, open, and power voicings.",
    kind: "source",
    iconClass: "fa-layer-group",
    iconTone: "cyan",
    navTooltip: "Advanced drop and shell voicings",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 30,
    previousNextOrder: 30,
    legacyTitle: "Chord Voicings",
    subtitle: "Advanced drop, shell, open, and inversion voicings",
    shellVisible: true,
  },
  {
    id: "circle",
    label: "Circle of Fifths",
    section: "Harmony & Theory",
    description: "Source rewrite of key relationships and circle navigation.",
    kind: "source",
    iconClass: "fa-circle-notch",
    iconTone: "amber",
    navTooltip: "Harmonic proximity and key relationships",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 40,
    previousNextOrder: 40,
    legacyTitle: "Circle of Fifths",
    subtitle: "Harmonic proximity and key relationships",
    shellVisible: true,
  },
  {
    id: "calculator",
    label: "Key Distance",
    section: "Harmony & Theory",
    description: "Source rewrite of key-center distance and shared-note comparison.",
    kind: "source",
    iconClass: "fa-map-location-dot",
    iconTone: "emerald",
    navTooltip: "Analyze distance and relationships between keys",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 50,
    previousNextOrder: 50,
    legacyTitle: "Key Distance",
    subtitle: "Analyze distance and relationships between keys",
    shellVisible: true,
  },
  {
    id: "intervals",
    label: "Interval Calculator",
    section: "Harmony & Theory",
    description: "Source rewrite of interval naming and semitone lookup.",
    kind: "source",
    iconClass: "fa-ruler",
    iconTone: "blue",
    navTooltip: "Calculate precise musical intervals",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 60,
    previousNextOrder: 60,
    legacyTitle: "Interval Calculator",
    subtitle: "Calculate precise musical intervals",
    shellVisible: true,
  },
  {
    id: "interchange",
    label: "Modal Interchange",
    section: "Harmony & Theory",
    description: "Source-side parallel-mode borrowing explorer.",
    kind: "source",
    iconClass: "fa-shuffle",
    iconTone: "rose",
    navTooltip: "Parallel modal borrowing explorer",
    legacySectionLabel: "Harmony & Theory",
    sectionOrder: 1,
    navOrder: 70,
    previousNextOrder: 70,
    legacyTitle: "Modal Interchange",
    subtitle: "Parallel modal borrowing explorer",
    shellVisible: true,
  },
  {
    id: "modes",
    label: "Western & Blues",
    section: "Exploration",
    description: "Source rewrite of western, blues, and jazz scale systems.",
    kind: "source",
    iconClass: "fa-mountain",
    iconTone: "blue",
    navTooltip: "Western modes and scale systems",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 10,
    previousNextOrder: 80,
    legacyTitle: "Western & Blues",
    subtitle: "Western modes and scale systems",
    shellVisible: true,
  },
  {
    id: "world",
    label: "World Scales",
    section: "Exploration",
    description: "Source rewrite of regional and experimental scales.",
    kind: "source",
    iconClass: "fa-globe",
    iconTone: "emerald",
    navTooltip: "Global and ethnic scale systems",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 20,
    previousNextOrder: 90,
    legacyTitle: "World Scales",
    subtitle: "Global and ethnic scale systems",
    shellVisible: true,
  },
  {
    id: "progressions",
    label: "Progressions",
    section: "Exploration",
    description: "Source rewrite of the progression library with resolved chords.",
    kind: "source",
    iconClass: "fa-arrow-right-arrow-left",
    iconTone: "indigo",
    navTooltip: "Iconic harmonic blueprints",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 30,
    previousNextOrder: 100,
    legacyTitle: "Progressions",
    subtitle: "Iconic harmonic blueprints",
    shellVisible: true,
  },
  {
    id: "finder",
    label: "Chord/Scale Finder",
    section: "Exploration",
    description: "Source rewrite of note-set identification and scale compatibility.",
    kind: "source",
    iconClass: "fa-search",
    iconTone: "teal",
    navTooltip: "Identify chords and scales from notes",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 40,
    previousNextOrder: 110,
    legacyTitle: "Chord/Scale Finder",
    subtitle: "Identify chords and scales from notes",
    shellVisible: true,
  },
  {
    id: "genres",
    label: "Genre Explorer",
    section: "Exploration",
    description: "Source-side genre DNA browser with extracted subgenre palettes.",
    kind: "source",
    iconClass: "fa-compact-disc",
    iconTone: "orange",
    navTooltip: "The DNA of global musical genres",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 50,
    previousNextOrder: 120,
    legacyTitle: "Genre Explorer",
    subtitle: "The DNA of global musical genres",
    shellVisible: true,
  },
  {
    id: "moods",
    label: "Mood Picker",
    section: "Exploration",
    description: "Source-side emotional palette explorer for scales and progressions.",
    kind: "source",
    iconClass: "fa-palette",
    iconTone: "pink",
    navTooltip: "Find harmony through emotion",
    legacySectionLabel: "Exploration",
    sectionOrder: 2,
    navOrder: 60,
    previousNextOrder: 130,
    legacyTitle: "Mood Picker",
    subtitle: "Find harmony through emotion",
    shellVisible: true,
  },
  {
    id: "phrasing",
    label: "Phrasing Tool",
    section: "Creative Lab",
    description: "Source-side melodic phrase generator with board and tab preview.",
    kind: "source",
    iconClass: "fa-wave-square",
    iconTone: "indigo",
    navTooltip: "Melodic motif and phrase generator",
    legacySectionLabel: "Creative Lab",
    sectionOrder: 3,
    navOrder: 10,
    previousNextOrder: 140,
    legacyTitle: "Phrasing Tool",
    subtitle: "Melodic motif and phrase generator",
    shellVisible: true,
  },
  {
    id: "studio",
    label: "Progression Studio",
    section: "Creative Lab",
    description: "Source-side Roman-numeral progression builder with favorites and MIDI export.",
    kind: "source",
    iconClass: "fa-microphone-lines",
    iconTone: "red",
    navTooltip: "Progression composer and analyzer",
    legacySectionLabel: "Creative Lab",
    sectionOrder: 3,
    navOrder: 20,
    previousNextOrder: 150,
    legacyTitle: "Progression Studio",
    subtitle: "Progression composer and analyzer",
    shellVisible: true,
  },
  {
    id: "songwriting",
    label: "Songwriting Lab",
    section: "Creative Lab",
    description: "Source-side lyric drafting, hook generation, rhyme analysis, and progression planning.",
    kind: "source",
    iconClass: "fa-pen-nib",
    iconTone: "amber",
    navTooltip: "Songwriting and lyric drafting tools",
    legacySectionLabel: "Creative Lab",
    sectionOrder: 3,
    navOrder: 30,
    previousNextOrder: 160,
    legacyTitle: "Songwriting Lab",
    subtitle: "Songwriting and lyric drafting tools",
    shellVisible: true,
  },
  {
    id: "microtonal",
    label: "Microtonal Lab",
    section: "Creative Lab",
    description: "Source-side tuning and temperament explorer with global playback settings.",
    kind: "source",
    iconClass: "fa-microchip",
    iconTone: "emerald",
    navTooltip: "Experimental quarter-tone research",
    legacySectionLabel: "Creative Lab",
    sectionOrder: 3,
    navOrder: 40,
    previousNextOrder: 170,
    legacyTitle: "Microtonal Lab",
    subtitle: "Experimental quarter-tone research",
    shellVisible: true,
  },
  {
    id: "metronome",
    label: "Metronome",
    section: "Performance",
    description: "Source-side metronome with presets, additive meters, and tap tempo.",
    kind: "source",
    iconClass: "fa-stopwatch",
    iconTone: "cyan",
    navTooltip: "High-precision practice metronome",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 10,
    previousNextOrder: 180,
    legacyTitle: "Metronome",
    subtitle: "High-precision practice metronome",
    shellVisible: true,
  },
  {
    id: "drums",
    label: "Drum Machine",
    section: "Performance",
    description: "Source-side step sequencer with generated genre patterns, swing, and MIDI export.",
    kind: "source",
    iconClass: "fa-drum",
    iconTone: "rose",
    navTooltip: "Humanized drum machine sequencer",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 20,
    previousNextOrder: 190,
    legacyTitle: "Drum Machine",
    subtitle: "Humanized drum machine sequencer",
    shellVisible: true,
  },
  {
    id: "customtuning",
    label: "Custom Tuning",
    section: "Performance",
    description: "Source-side custom instrument and fretboard layout builder.",
    kind: "source",
    iconClass: "fa-wrench",
    iconTone: "zinc",
    navTooltip: "Custom instrument and string tunings",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 30,
    previousNextOrder: 200,
    legacyTitle: "Custom Tuning",
    subtitle: "Custom instrument and string tunings",
    legacyNavId: "tuning",
    shellVisible: true,
  },
  {
    id: "notation",
    label: "Notation",
    section: "Performance",
    description: "Source-side staff writer with clef switching, MIDI export, and piano-roll preview.",
    kind: "source",
    iconClass: "fa-file-lines",
    iconTone: "blue",
    navTooltip: "Standard staff notation writer",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 40,
    previousNextOrder: 210,
    legacyTitle: "Notation",
    subtitle: "Standard staff notation writer",
    shellVisible: true,
  },
  {
    id: "tablature",
    label: "Tablature Tool",
    section: "Performance",
    description: "Source-side fretboard tab builder with playback, export, and MIDI pitch analysis.",
    kind: "source",
    iconClass: "fa-guitar",
    iconTone: "orange",
    navTooltip: "Source-only tablature editor kept adjacent to notation tools",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 45,
    previousNextOrder: 215,
    legacyTitle: "Tablature Tool",
    subtitle: "Source-only tablature editor layered into the restored shell",
    shellVisible: false,
  },
  {
    id: "piano",
    label: "Instrument View",
    section: "Performance",
    description: "Source-side piano and fretboard explorer.",
    kind: "source",
    iconClass: "fa-keyboard",
    iconTone: "indigo",
    navTooltip: "Source-only instrument board explorer retained outside the legacy nav",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 47,
    previousNextOrder: 217,
    legacyTitle: "Instrument View",
    subtitle: "Source-only instrument board explorer retained inside the legacy shell",
    shellVisible: false,
  },
  {
    id: "rhythmic",
    label: "Rhythmic Lab",
    section: "Performance",
    description: "Source-side drills for polyrhythms, syncopation, tuplets, and accent slicing.",
    kind: "source",
    iconClass: "fa-drum-steelpan",
    iconTone: "teal",
    navTooltip: "Polyrhythms, syncopation, tuplets, beat-slicing",
    legacySectionLabel: "Performance",
    sectionOrder: 4,
    navOrder: 50,
    previousNextOrder: 220,
    legacyTitle: "Rhythmic Lab",
    subtitle: "Polyrhythms, syncopation, tuplets, and beat-slicing",
    shellVisible: true,
  },
  {
    id: "guide",
    label: "Theory Guide",
    section: "Reference & Learning",
    description: "Source-side searchable theory reference.",
    kind: "source",
    iconClass: "fa-book-open",
    iconTone: "blue",
    navTooltip: "Quick theory and intervals guide",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 10,
    previousNextOrder: 230,
    legacyTitle: "Theory Reference",
    subtitle: "Quick theory and intervals guide",
    legacyNavId: "theory",
    shellVisible: true,
  },
  {
    id: "grimoire",
    label: "Grimoire",
    section: "Reference & Learning",
    description: "Source-side advanced scale, mode, and chord catalog mapped to the active root.",
    kind: "source",
    iconClass: "fa-scroll",
    iconTone: "amber",
    navTooltip: "The Ultimate Keyboard Grimoire catalog",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 20,
    previousNextOrder: 240,
    legacyTitle: "Grimoire",
    subtitle: "The Ultimate Keyboard Grimoire catalog",
    shellVisible: true,
  },
  {
    id: "ear",
    label: "Ear Trainer",
    section: "Reference & Learning",
    description: "Source-side relative pitch drills for notes, intervals, chords, melody, and rhythm.",
    kind: "source",
    iconClass: "fa-headphones",
    iconTone: "purple",
    navTooltip: "Adaptive pitch and interval trainer",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 30,
    previousNextOrder: 250,
    legacyTitle: "Ear Trainer",
    subtitle: "Adaptive pitch and interval trainer",
    shellVisible: true,
  },
  {
    id: "quiz",
    label: "Knowledge Quiz",
    section: "Reference & Learning",
    description: "Source-side theory quiz with difficulty tiers, typed answers, and timed mode.",
    kind: "source",
    iconClass: "fa-graduation-cap",
    iconTone: "green",
    navTooltip: "Test your music theory knowledge",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 40,
    previousNextOrder: 260,
    legacyTitle: "Knowledge Quiz",
    subtitle: "Test your music theory knowledge",
    shellVisible: true,
  },
  {
    id: "learning",
    label: "Learning Paths",
    section: "Reference & Learning",
    description: "Source-side guided track progression system with XP milestones.",
    kind: "source",
    iconClass: "fa-chalkboard-user",
    iconTone: "amber",
    navTooltip: "Structured theory curriculum",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 50,
    previousNextOrder: 270,
    legacyTitle: "Learning Paths",
    subtitle: "Structured theory curriculum",
    shellVisible: true,
  },
  {
    id: "scalebuilder",
    label: "Scale Builder",
    section: "Reference & Learning",
    description: "Source-side custom scale designer with presets, harmonization, and local saves.",
    kind: "source",
    iconClass: "fa-sliders-h",
    iconTone: "teal",
    navTooltip: "Custom scale builder",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 60,
    previousNextOrder: 280,
    legacyTitle: "Scale Builder",
    subtitle: "Custom scale builder",
    shellVisible: true,
  },
  {
    id: "chordanalyzer",
    label: "Chord Analyzer",
    section: "Reference & Learning",
    description: "Source-side chord symbol parser with inversions, scale fits, and key-role hints.",
    kind: "source",
    iconClass: "fa-search",
    iconTone: "pink",
    navTooltip: "Chord symbol analysis and alternatives",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 70,
    previousNextOrder: 290,
    legacyTitle: "Chord Analyzer",
    subtitle: "Chord symbol analysis and alternatives",
    shellVisible: true,
  },
  {
    id: "harmony",
    label: "Advanced Harmony",
    section: "Reference & Learning",
    description: "Source-side harmonic function, melodic-minor modes, and upper-structure triads.",
    kind: "source",
    iconClass: "fa-sitemap",
    iconTone: "lime",
    navTooltip: "Melodic minor, upper structures, harmonic functions",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 80,
    previousNextOrder: 300,
    legacyTitle: "Advanced Harmony",
    subtitle: "Melodic minor, upper structures, and harmonic functions",
    shellVisible: true,
  },
  {
    id: "modulate",
    label: "Modulation Lab",
    section: "Reference & Learning",
    description: "Source-side key-change finder with pivot chords and parallel major/minor comparison.",
    kind: "source",
    iconClass: "fa-arrow-right-arrow-left",
    iconTone: "orange",
    navTooltip: "Modulation finder and key comparison",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 90,
    previousNextOrder: 310,
    legacyTitle: "Modulation Lab",
    subtitle: "Modulation finder and key comparison",
    shellVisible: true,
  },
  {
    id: "favorites",
    label: "My Favorites",
    section: "Reference & Learning",
    description: "Source-side saved chords, scales, and progressions with legacy migration.",
    kind: "source",
    iconClass: "fa-star",
    iconTone: "yellow",
    navTooltip: "Your saved musical discoveries",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 100,
    previousNextOrder: 320,
    legacyTitle: "My Favorites",
    subtitle: "Your saved musical discoveries",
    shellVisible: true,
  },
  {
    id: "mixing",
    label: "Mixing Guide",
    section: "Reference & Learning",
    description: "Source-side mixing starting points for instrument families and session roles.",
    kind: "source",
    iconClass: "fa-sliders",
    iconTone: "cyan",
    navTooltip: "Source-only mixing reference retained outside the legacy nav",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 105,
    previousNextOrder: 325,
    legacyTitle: "Mixing Guide",
    subtitle: "Source-only production reference retained inside the restored shell",
    shellVisible: false,
  },
  {
    id: "recording",
    label: "Recording Guide",
    section: "Reference & Learning",
    description: "Source-side recording workflow checklists and genre-specific tracking notes.",
    kind: "source",
    iconClass: "fa-microphone",
    iconTone: "rose",
    navTooltip: "Source-only recording reference retained outside the legacy nav",
    legacySectionLabel: "Reference & Learning",
    sectionOrder: 5,
    navOrder: 110,
    previousNextOrder: 330,
    legacyTitle: "Recording Guide",
    subtitle: "Source-only recording reference retained inside the restored shell",
    shellVisible: false,
  },
];

export const featureRegistry = featureDefinitions.slice().sort((left, right) => {
  if (left.sectionOrder !== right.sectionOrder) {
    return left.sectionOrder - right.sectionOrder;
  }

  if (left.navOrder !== right.navOrder) {
    return left.navOrder - right.navOrder;
  }

  return left.label.localeCompare(right.label);
});

export const featureRegistryById = new Map(featureRegistry.map((feature) => [feature.id, feature]));

export const sourceFeatureIds = new Set(
  featureRegistry.filter((feature) => feature.kind === "source").map((feature) => feature.id),
);

export const sourceFeaturesInPreviousNextOrder = featureRegistry
  .filter((feature) => feature.kind === "source")
  .slice()
  .sort((left, right) => left.previousNextOrder - right.previousNextOrder);

export const shellFeatures = featureRegistry.filter(
  (feature) => feature.kind === "source" && feature.shellVisible,
);

export function getFeatureDefinition(featureId: string | null | undefined) {
  if (!featureId) return null;
  return featureRegistryById.get(featureId) ?? null;
}

export function getShellSections() {
  const groupedSections = new Map<string, FeatureDefinition[]>();

  shellFeatures.forEach((feature) => {
    const current = groupedSections.get(feature.legacySectionLabel) ?? [];
    current.push(feature);
    groupedSections.set(feature.legacySectionLabel, current);
  });

  return Array.from(groupedSections.entries()).map(([label, features]) => ({
    label,
    features: features.slice().sort((left, right) => left.navOrder - right.navOrder),
  }));
}

export function getAdjacentSourceFeatures(featureId: string | null | undefined) {
  if (!featureId) {
    return { previousFeature: null, nextFeature: null };
  }

  const currentIndex = sourceFeaturesInPreviousNextOrder.findIndex((feature) => feature.id === featureId);
  if (currentIndex === -1) {
    return { previousFeature: null, nextFeature: null };
  }

  return {
    previousFeature:
      currentIndex > 0 ? sourceFeaturesInPreviousNextOrder[currentIndex - 1] : null,
    nextFeature:
      currentIndex < sourceFeaturesInPreviousNextOrder.length - 1
        ? sourceFeaturesInPreviousNextOrder[currentIndex + 1]
        : null,
  };
}
