export interface FeatureDefinition {
  id: string;
  label: string;
  section: string;
  description: string;
  kind: "source" | "legacy";
  legacyView?: string;
}

export const featureRegistry: FeatureDefinition[] = [
  {
    id: "chords",
    label: "Diatonic Chords",
    section: "Harmony & Theory",
    description: "Source rewrite of scale-degree triads and seventh chords.",
    kind: "source",
  },
  {
    id: "allchords",
    label: "All Chord Types",
    section: "Harmony & Theory",
    description: "Source rewrite of the chord formula and interval catalog.",
    kind: "source",
  },
  {
    id: "voicings",
    label: "Chord Voicings",
    section: "Harmony & Theory",
    description: "Source rewrite of inversion, drop, shell, open, and power voicings.",
    kind: "source",
  },
  {
    id: "circle",
    label: "Circle of Fifths",
    section: "Harmony & Theory",
    description: "Source rewrite of key relationships and circle navigation.",
    kind: "source",
  },
  {
    id: "calculator",
    label: "Key Distance",
    section: "Harmony & Theory",
    description: "Source rewrite of key-center distance and shared-note comparison.",
    kind: "source",
  },
  {
    id: "notation",
    label: "Notation Writer",
    section: "Harmony & Theory",
    description: "Source-side staff writer with clef switching, MIDI export, and piano-roll preview.",
    kind: "source",
  },
  {
    id: "tablature",
    label: "Tablature Tool",
    section: "Harmony & Theory",
    description: "Source-side fretboard tab builder with playback, export, and MIDI pitch analysis.",
    kind: "source",
  },
  {
    id: "intervals",
    label: "Interval Calculator",
    section: "Harmony & Theory",
    description: "Source rewrite of interval naming and semitone lookup.",
    kind: "source",
  },
  {
    id: "interchange",
    label: "Modal Interchange",
    section: "Harmony & Theory",
    description: "Source-side parallel-mode borrowing explorer.",
    kind: "source",
  },
  {
    id: "chordanalyzer",
    label: "Chord Analyzer",
    section: "Harmony & Theory",
    description: "Source-side chord symbol parser with inversions, scale fits, and key-role hints.",
    kind: "source",
  },
  {
    id: "harmony",
    label: "Advanced Harmony",
    section: "Harmony & Theory",
    description: "Source-side harmonic function, melodic-minor modes, and upper-structure triads.",
    kind: "source",
  },
  {
    id: "modulate",
    label: "Modulation Lab",
    section: "Harmony & Theory",
    description: "Source-side key-change finder with pivot chords and parallel major/minor comparison.",
    kind: "source",
  },
  {
    id: "modes",
    label: "Western & Blues",
    section: "Exploration",
    description: "Source rewrite of western, blues, and jazz scale systems.",
    kind: "source",
  },
  {
    id: "world",
    label: "World Scales",
    section: "Exploration",
    description: "Source rewrite of regional and experimental scales.",
    kind: "source",
  },
  {
    id: "scalebuilder",
    label: "Scale Builder",
    section: "Exploration",
    description: "Source-side custom scale designer with presets, harmonization, and local saves.",
    kind: "source",
  },
  {
    id: "progressions",
    label: "Progressions",
    section: "Exploration",
    description: "Source rewrite of the progression library with resolved chords.",
    kind: "source",
  },
  {
    id: "finder",
    label: "Chord/Scale Finder",
    section: "Exploration",
    description: "Source rewrite of note-set identification and scale compatibility.",
    kind: "source",
  },
  {
    id: "genres",
    label: "Genre Explorer",
    section: "Exploration",
    description: "Source-side genre DNA browser with extracted subgenre palettes.",
    kind: "source",
  },
  {
    id: "moods",
    label: "Mood Picker",
    section: "Exploration",
    description: "Source-side emotional palette explorer for scales and progressions.",
    kind: "source",
  },
  {
    id: "phrasing",
    label: "Phrasing Tool",
    section: "Creative",
    description: "Source-side melodic phrase generator with board and tab preview.",
    kind: "source",
  },
  {
    id: "studio",
    label: "Progression Studio",
    section: "Creative",
    description: "Source-side Roman-numeral progression builder with favorites and MIDI export.",
    kind: "source",
  },
  {
    id: "songwriting",
    label: "Songwriting Lab",
    section: "Creative",
    description: "Source-side lyric drafting, hook generation, rhyme analysis, and progression planning.",
    kind: "source",
  },
  {
    id: "piano",
    label: "Instrument View",
    section: "Performance",
    description: "Source-side piano and fretboard explorer.",
    kind: "source",
  },
  {
    id: "microtonal",
    label: "Microtonal Lab",
    section: "Performance",
    description: "Source-side tuning and temperament explorer with global playback settings.",
    kind: "source",
  },
  {
    id: "customtuning",
    label: "Custom Tuning",
    section: "Performance",
    description: "Source-side custom instrument and fretboard layout builder.",
    kind: "source",
  },
  {
    id: "metronome",
    label: "Metronome",
    section: "Performance",
    description: "Source-side metronome with presets, additive meters, and tap tempo.",
    kind: "source",
  },
  {
    id: "drums",
    label: "Drum Machine",
    section: "Performance",
    description: "Source-side step sequencer with generated genre patterns, swing, and MIDI export.",
    kind: "source",
  },
  {
    id: "rhythmic",
    label: "Rhythmic Lab",
    section: "Performance",
    description: "Source-side drills for polyrhythms, syncopation, tuplets, and accent slicing.",
    kind: "source",
  },
  {
    id: "ear",
    label: "Ear Trainer",
    section: "Performance",
    description: "Source-side relative pitch drills for notes, intervals, chords, melody, and rhythm.",
    kind: "source",
  },
  {
    id: "quiz",
    label: "Quiz",
    section: "Learning",
    description: "Source-side theory quiz with difficulty tiers, typed answers, and timed mode.",
    kind: "source",
  },
  {
    id: "learning",
    label: "Learning Paths",
    section: "Learning",
    description: "Source-side guided track progression system with XP milestones.",
    kind: "source",
  },
  {
    id: "guide",
    label: "Theory Guide",
    section: "Learning",
    description: "Source-side searchable theory reference.",
    kind: "source",
  },
  {
    id: "grimoire",
    label: "Grimoire",
    section: "Learning",
    description: "Source-side advanced scale, mode, and chord catalog mapped to the active root.",
    kind: "source",
  },
  {
    id: "favorites",
    label: "Favorites",
    section: "Learning",
    description: "Source-side saved chords, scales, and progressions with legacy migration.",
    kind: "source",
  },
  {
    id: "mixing",
    label: "Mixing Guide",
    section: "Learning",
    description: "Source-side mixing starting points for instrument families and session roles.",
    kind: "source",
  },
  {
    id: "recording",
    label: "Recording Guide",
    section: "Learning",
    description: "Source-side recording workflow checklists and genre-specific tracking notes.",
    kind: "source",
  },
];

export const sourceFeatureIds = new Set(
  featureRegistry.filter((feature) => feature.kind === "source").map((feature) => feature.id),
);
